FROM node:20

WORKDIR /app/apps/backend

COPY apps/backend/package.json ./
COPY packages ./packages

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install

COPY apps/backend ./

CMD ["pnpm", "run", "dev"]