FROM node:20

# Receive the app name as a build argument
ARG APP_NAME
ENV APP_NAME=${APP_NAME}

WORKDIR /app/apps/${APP_NAME}

COPY apps/${APP_NAME}/package.json ./
COPY packages ./packages

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install

COPY apps/${APP_NAME} ./

CMD ["pnpm", "run", "dev"]
